###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8080
spring.application.name: config-client-refresh
spring.profiles.active: dev

#logging.level:
#  root: INFO
#  org.springframework.cloud.config: TRACE
#  org.springframework.boot: TRACE

management:
  endpoints.web.exposure.include: env, health, refresh

spring.config.import: configserver:http://localhost:8888

my.custom.property: "classpath - src/main/resources/application.yaml"