my.custom.property: "Config Server - config-repo/config-client-local/config-client-local-dev.yaml"

spring.cloud.config:
  allow-override: true
  override-none: true
  override-system-properties: false
