###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8888
spring.application.name: config-server
spring.profiles.active: native

---

spring.cloud.config.server:
  native:
    search-locations:
      - "file:../config-repo/shared"
      - "file:../config-repo/{application}"
  git:
    basedir: clone-repo
    clone-on-start: true
    default-label: main
    refresh-rate: 1
    skip-ssl-validation: true
    timeout: 5
    uri: https://github.com/bkjam/config-server-order
    search-paths:
      - "config-repo/shared"
      - "config-repo/{application}"

---

spring.config.activate.on-profile: local
spring.cloud.config.server:
  git:
    clone-on-start: false
    uri: file:../
