###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8888
spring.application.name: config-server

---

spring.cloud.config.server:
  git:
    basedir: clone-repo
    clone-on-start: true
    default-label: main
    refresh-rate: 1
    skip-ssl-validation: true
    timeout: 5
    uri: https://github.com/bkjam/config-server-order
    search-paths:
      - "config-repo/shared"
      - "config-repo/{application}"

---
#spring.config.activate.on-profile: local
#spring.cloud.config.server.git.uri: file:///home/amanda/Desktop/config-server-order/config-repo
